###
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "Maria",
    "email": "maria@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "carlos@gmail.com",
    "password": "123456"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjYXJsb3NAZ21haWwuY29tIiwiaWF0IjoxNjM1MDQ5MTgzLCJleHAiOjE2Mzc2NDExODN9.iqykOfW3T312CagKg786rHeaGkJgECg3KnBaTshRE0s